### ISSUE TITLE
Please update the documentation bro.. please.

### ISSUE THREAD

**Issue by snehashishalder** [stakeordie/griptape.js#106]
Please update the documentation bro.. please.

i got some error during run time.
https://github.com/stakeordie/griptape-docs/tree/main/docs/tutorial

![Screenshot from 2021-11-23 00-13-49](https://user-images.githubusercontent.com/84185314/142918614-8072efb6-259e-4ac0-ad88-024a3b6b3d79.png)
![Screenshot from 2021-11-23 00-14-25](https://user-images.githubusercontent.com/84185314/142918628-5c206fa9-5927-4336-a91a-708199b05608.png)
![Screenshot from 2021-11-23 00-13-14](https://user-images.githubusercontent.com/84185314/142918638-d2fb1fb7-9c27-470b-b022-ab054458d725.png)

**Comment by luis-stakeordie** [comment]
Hi @snehashishalder.

I really encourage you to look at the docs https://docs.griptapejs.com and not directly on the repo.

Part of the reason we removed from the site is due to the fact they are outdated.

The current site has a complete guide to walk you through how to use Griptape.

**Comment by snehashishalder** [comment]
thanks,  please add some examples for latest stable version.

**Comment by snehashishalder** [comment]
> Hi @snehashishalder.
> 
> I really encourage you to look at the docs https://docs.griptapejs.com and not directly on the repo.
> 
> Part of the reason we removed from the site is due to the fact they are outdated.
> 
> The current site has a complete guide to walk you through how to use Griptape.

thanks, please add some examples for latest stable version.
