### ISSUE TITLE
Fix `deposit` message in `snip20Def`

### ISSUE THREAD

**Issue by David-Sod** [stakeordie/griptape.js#122]

**Comment by David-Sod** [comment]
The `transfer` message is working fine, there is only need to transferAmount in `deposit`

**Comment by luis-espinoza** [comment]
@David-Sod I think the reason of the fix is not because it fails, but because it does nothing.

**Comment by David-Sod** [comment]
@luis-espinoza yeah I looked into the docs [here](https://github.com/SecretFoundation/SNIPs/blob/master/SNIP-20.md#Transfer) and  I think `transfer` does not need transfer amount since transfer sends actually snip20 tokens vs deposit that burns some native tokens and get you the equivalent in the snip20. Am I wrong ?

**Comment by David-Sod** [comment]
![image](https://user-images.githubusercontent.com/81386118/152583380-44754c86-2d66-4475-af94-76808ff54d39.png)

This what transfer looks like, the amount is sent in the msg instead of transferAmount
