### ISSUE TITLE
Issue with Webpack 5 and some internal Griptape libraries

### ISSUE THREAD

**Issue by luiseel** [stakeordie/griptape.js#144]
![image](https://user-images.githubusercontent.com/79593471/153935803-73f0c450-1214-476b-b7f9-e7234aa36c50.png)
![image](https://user-images.githubusercontent.com/79593471/153935835-876dc661-21d2-4af2-bcdd-67a9c0fa781d.png)

**Comment by 0xhiroki** [comment]
Has anyone figured this out?

**Comment by luiseel** [comment]
> Has anyone figured this out?

I have found this resource that should help: https://github.com/cosmos/cosmjs#webpack-configs

**Comment by luiseel** [comment]
I'm going to close this issue due to the fact this has to do with Webpack and not necessarily with Griptape.
