### ISSUE TITLE
stores permits in localStorage griptape.js, but still sets permit Context from localStorage querypermit${address + contractAddress}

### ISSUE THREAD

**Issue by VPringle97** [stakeordie/griptape.js#179]
![image](https://user-images.githubusercontent.com/95774978/161855206-b3a0e1ae-4856-4fee-86c9-7ff20887e621.png)

**Comment by luiseel** [comment]
![image](https://user-images.githubusercontent.com/79593471/162254738-2e0fed18-41bb-4ef3-8048-6480945476a6.png)
