### ISSUE TITLE
Function for display of wallet name

### ISSUE THREAD

**Issue by AustinWoetzel** [stakeordie/griptape.js#183]
Add function to display wallet name rather than only having an option for address. It seems like most apps across Cosmos have moved towards display of name or name + address rather than address only.

**Comment by luiseel** [comment]
@VPringle97 

Add `getWalletInfo`:

```ts
interface WalletInfo {
  address: string;
  name: string;
}
getWalletInfo(): Promise<WalletInfo>;
```

### Requirements

- Add `getName` to `AccountProvider` https://github.com/stakeordie/griptape.js/blob/2acff88f60e78351dfd5f329e8ed89b9f8f47fe5/src/bootstrap.ts#L47
`getName: () => string`
- Get name using [`keplr.getKey(chainId: string): Promise<{ name: string, ... }>`](https://docs.keplr.app/api/#get-address-public-key) and return it https://github.com/stakeordie/griptape.js/blob/2acff88f60e78351dfd5f329e8ed89b9f8f47fe5/src/bootstrap.ts#L238
- Use provider to get `name` and `address` https://github.com/stakeordie/griptape.js/blob/2acff88f60e78351dfd5f329e8ed89b9f8f47fe5/src/bootstrap.ts#L76
