### ISSUE TITLE
Not error is being thrown when adding an `undefined` viewing key

### ISSUE THREAD

**Issue by luis-stakeordie** [stakeordie/griptape.js#23]
When using the `viewingKeyManager.add` and as the second argument you pass `undefined`, you don't get any error,
and a viewing key gets added without `key`. 

**To Reproduce**

1. import `viewingKeyManager` from `@stakeordie/griptape.js`
2. Define a simple contract to add a viewing key for
3. Use the `viewingKeyManager.add` method and pass `undefined` as the second parameter
3. Check `localStorage`

**Expected behavior**

It should throw an error due to the fact that you are adding an undefined viewing key.

**Comment by David-Sod** [comment]
Closing this issue, solved in the PR `#35`
